version: '3.8'
services:
  db:
    image: mongo:latest
    networks:
      - vista-portal-network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: vista-portal
      MONGO_INITDB_ROOT_PASSWORD: rfh98LKJh4a0x9u4Ld893mak211j

  backend:
    build: ./vista-portal-backend
    image: nerevarishe/vista-portal-backend:latest
    volumes:
      - uploads:/srv/www/vista_portal_api/static/uploads
    ports:
      - 5000:5000
    networks:
      - vista-portal-network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: vista_portal_api
      MONGO_INITDB_ROOT_PASSWORD: rfh98LKJh4a0x9u4Ld893mak211j
      
  frontend:
    build: ./vista-portal-frontend
    image: nerevarishe/vista-portal-frontend:latest
    ports:
      - 8080:80
    networks:
      - vista-portal-network
    restart: always

volumes:
  uploads:

networks:
  vista-portal-network:
    name: vista-portal-network
