version: '3.8'
services:
  db:
    image: mongo:latest
    networks:
      - vista-portal-network
    restart: always

  backend:
    image: nerevarishe/vista-portal-backend:latest
    volumes:
      - uploads:/srv/www/vista-portal-backend/static/uploads
    ports:
      - 5000:5000
    networks:
      - vista-portal-network
    restart: always

  frontend:
    image: nerevarishe/vista-portal-frontend:latest
    ports:
      - 8080:80
    networks:
      - vista-portal-network
    restart: always

volumes:
  uploads:

networks:
  vista-portal-network:
    name: vista-portal-network
